export const thanglish = {
  'A LITTLE EVERY DAY. A LONG WAY AHEAD.': 'KONJAM KONJAMA. NAMBIKKAIYODA.',
  'Your next chapter': 'Un vegam.', 'starts here.': 'Un vetri.',
  'Big dreams begin with small discoveries.': 'Puriyala na parava illa. Thirumba padikkalaam.',
  'Make a little room for learning today.': 'Oru chinna step. Oru pudhu nambikkai.',
  'A fresh page. A fresh start.': 'Oru pakkam. Oru pudhu aarambam.',
  'FIVE SUBJECTS. ENDLESS POSSIBILITIES.': 'AINDHU PAADANGAL. UNAKKAANA PAADHAI.',
  Tamil: 'Tamil', English: 'English', Maths: 'Kanakku', Science: 'Ariviyal', Social: 'Samuga ariviyal',
  'Rooted in Tamil Nadu. Ready for your tomorrow.': 'Tamil Nadu paadangal. Un vegathil katrukkalaam.',
  'YOUR SPACE TO GROW': 'UNAKKAANA KATRAL IDAM',
  'A new beginning.': 'Pudhusa aarambikkalaam.', 'Welcome back.': 'Vanakkam, nanba.',
  'Your learning journey starts with you.': 'Un katral payanam, un vegathil.',
  'Good to see you. Let’s turn a new page.': 'Avasaram illa. Serndhu katrukkalaam.',
  'Log in': 'Ulle vaanga', 'Create account': 'Kanakku uruvaakku',
  'Your name': 'Un peyar', 'What should we call you?': 'Unnai eppadi koopidalaam?',
  'Email address': 'Email mugavari', Password: 'Password',
  'At least 12 characters': 'Kuraindhadhu 12 ezhuthugal', 'Enter your password': 'Un password-ai podu',
  'Study medium': 'Padikkum mozhi', 'Your own little learning space': 'Unakena oru katral idam',
  'Start my chapter': 'En payanathai thodangu', 'Let’s get learning': 'Vaanga, padikkalaam',
  'The page is ready. Account connection is coming next; no details have been sent or saved.': 'Idhu preview mattum. Account innum connect aagala; un details anuppavum save pannavum illa.',
  'Already have an account?': 'Erkanave kanakku irukka?', 'New around here?': 'Inga pudhusa?',
  'Make a fresh start': 'Pudhusa thodangu',
  'One syllabus. Your own pace.': 'Ore paadathittam. Un sondha vegam.',
  'Tamil & English medium · Tamil Nadu Class 10': 'Tamil & English vazhi · Tamil Nadu 10-aam vaguppu',
  'Made for the way you learn.': 'Nee kathukkura vidhathukkaaga.',
};

export const learningCopy = {
  'ta-Latn': {
    kicker: 'UN VEGAM PODHUM', title: 'Puriyum varai, serndhu padikkalaam.',
    description: 'Konjam extra neram venuma? Adhu okay. Siru padigalil aarambithu, un nambikkaiyai valarthukkalaam.',
    preview: 'Sample lesson · AI innum connect aagala',
    modes: ['Nidhaanama', 'Seeraana vegam', 'Challenge'],
    modeNotes: ['Oru nerathil oru step. Avasaram illa.', 'Mukkiya padigal, appuram oru practice.', 'Neeye muyarchi sei. Udhavi eppovum irukku.'],
    tabs: ['AI aasiriyar', 'Practice test', 'Revision'],
    featureNotes: ['Sandhegangalukku eliya vilakkam', 'Muyarchi sei. Feedback paaru.', 'Mukkiya karuthugalai ninaivupaduthu'],
    question: '2x + 4 = 10. x enna?', tutor: 'Serndhu solve pannalaam.',
    steps: ['Rendu pakkamum 4-ai kazhikkalaam: 2x = 6.', 'Rendu pakkamum 2-aal vagukkalaam: x = 3.', 'Check pannalaam: 2 × 3 + 4 = 10. Sari!'],
    next: 'Adutha step', restart: 'Marubadiyum paaru', hint: 'Oru hint venum',
    prompt: 'Un badhilai therndhedu. Timer illa.',
    correct: 'Sariyaana badhil! 2 × 3 + 4 = 10.', wrong: 'Nalla muyarchi. Mudhalil 4-ai kazhithu, appuram 2-aal vaguthu paaru.',
    retry: 'Thirumba muyarchi sei', recap: 'Ninaivil vechukko',
    recapText: 'Equation balance-aaga irukkanum. Oru pakkam seivadha, innoru pakkamum seiyanum.',
    recapItems: ['Mudhalil 4-ai kazhi', 'Aduthu 2-aal vagu', 'Badhilai substitute panni check sei'],
    roadmap: 'AI tutor, un paadathitta tests, progress tracking: adutha kattathil.',
    noTimer: 'Timer illa', repeat: 'Ethana murai venaalum', noRank: 'Oppidu illa', step: 'Padi',
  },
  en: {
    kicker: 'YOUR PACE IS ENOUGH', title: 'Understanding comes first. Always.',
    description: 'Need a little more time? You belong here. Start with small steps and build confidence, one idea at a time.',
    preview: 'Sample lesson · AI not connected yet',
    modes: ['Step by step', 'Steady pace', 'Challenge'],
    modeNotes: ['One small step at a time. No rush.', 'The key steps, then a little practice.', 'Try it yourself. Help is always here.'],
    tabs: ['AI tutor', 'Practice test', 'Revision'], featureNotes: ['Simple explanations for your questions', 'Try an answer. Get helpful feedback.', 'Come back to the ideas that matter'],
    question: '2x + 4 = 10. What is x?', tutor: 'Let’s work through it together.',
    steps: ['Subtract 4 from both sides: 2x = 6.', 'Divide both sides by 2: x = 3.', 'Check: 2 × 3 + 4 = 10. It works!'],
    next: 'Next step', restart: 'See it again', hint: 'Show a hint', prompt: 'Choose your answer. There is no timer.',
    correct: 'You got it! 2 × 3 + 4 = 10.', wrong: 'Good try. Subtract 4 first, then divide both sides by 2.', retry: 'Try again',
    recap: 'Keep this little idea', recapText: 'Keep an equation balanced. Whatever you do to one side, do to the other side too.',
    recapItems: ['Subtract 4 first', 'Then divide by 2', 'Substitute your answer to check'],
    roadmap: 'Connected AI tutoring, syllabus tests and progress tracking are planned next.',
    noTimer: 'No timers', repeat: 'Repeat any time', noRank: 'No comparisons', step: 'Step',
  },
  ta: {
    kicker: 'உன் வேகமே போதும்', title: 'புரிதலுக்கே முதல் இடம். எப்போதும்.',
    description: 'கொஞ்சம் கூடுதல் நேரம் வேண்டுமா? பரவாயில்லை. சிறிய படிகளில் தொடங்கி, நம்பிக்கையுடன் முன்னேறலாம்.',
    preview: 'மாதிரிப் பாடம் · AI இன்னும் இணைக்கப்படவில்லை',
    modes: ['படிப்படியாக', 'சீரான வேகம்', 'சவால்'],
    modeNotes: ['ஒரு நேரத்தில் ஒரு படி. அவசரம் இல்லை.', 'முக்கிய படிகள், பிறகு சிறு பயிற்சி.', 'நீயே முயற்சி செய். உதவி எப்போதும் உண்டு.'],
    tabs: ['AI ஆசிரியர்', 'பயிற்சித் தேர்வு', 'மீள்பார்வை'], featureNotes: ['கேள்விகளுக்கு எளிய விளக்கம்', 'முயற்சி செய். கருத்தைப் பெறு.', 'முக்கிய கருத்துகளை நினைவுபடுத்து'],
    question: '2x + 4 = 10. x என்ன?', tutor: 'சேர்ந்து தீர்வு காணலாம்.',
    steps: ['இரு பக்கமும் 4-ஐக் கழிக்கலாம்: 2x = 6.', 'இரு பக்கமும் 2-ஆல் வகுக்கலாம்: x = 3.', 'சரிபார்: 2 × 3 + 4 = 10. சரி!'],
    next: 'அடுத்த படி', restart: 'மீண்டும் பார்', hint: 'குறிப்பு காட்டு', prompt: 'உன் விடையைத் தேர்ந்தெடு. நேர வரம்பு இல்லை.',
    correct: 'சரியான விடை! 2 × 3 + 4 = 10.', wrong: 'நல்ல முயற்சி. முதலில் 4-ஐக் கழித்து, பிறகு இரு பக்கமும் 2-ஆல் வகுத்துப் பார்.', retry: 'மீண்டும் முயற்சி செய்',
    recap: 'இதை நினைவில் கொள்', recapText: 'சமன்பாட்டின் சமநிலையைப் பேண வேண்டும். ஒரு பக்கம் செய்வதை மற்றொரு பக்கமும் செய்ய வேண்டும்.',
    recapItems: ['முதலில் 4-ஐக் கழி', 'பிறகு 2-ஆல் வகு', 'விடையைப் பதிலிட்டு சரிபார்'],
    roadmap: 'இணைக்கப்பட்ட AI ஆசிரியர், பாடத்திட்டத் தேர்வுகள், முன்னேற்றப் பதிவு அடுத்த கட்டத்தில்.',
    noTimer: 'நேர வரம்பில்லை', repeat: 'எப்போது வேண்டுமானாலும்', noRank: 'ஒப்பீடு இல்லை', step: 'படி',
  },
};

export const shellCopy = {
  'ta-Latn': {
    tagline: 'Nee kathukkura vidhathukkaaga.', board: 'TAMIL NADU STATE BOARD', navigation: 'Learning levels', menu: 'Menu', closeMenu: 'Menu-vai moodu', languageLabel: 'Mozhi', homeLabel: 'Padi and Go mugappu',
    routes: { chat: 'Learn', practice: 'Practise', tests: 'Test', progress: 'Improve', login: 'Log in' },
    routeNotes: { chat: 'Chatbot', practice: 'Topic questions', tests: 'Mock tests', progress: 'Revision & progress' },
    directAccess: 'Learning preview-kku po', sampleComing: 'Indha sample module adutha task-il varum.',
    loginKicker: 'UNAKKAANA KATRAL IDAM', loginTitle: 'Vanakkam, nanba.', signupTitle: 'Pudhusa aarambikkalaam.', loginSubtitle: 'Avasaram illa. Serndhu kathukkalaam.', signupSubtitle: 'Un katral payanam, un vegathil.',
    login: 'Ulle vaanga', signup: 'Kanakku uruvaakku', name: 'Un peyar', namePlaceholder: 'Unnai eppadi koopidalaam?', email: 'Email mugavari', password: 'Password', passwordPlaceholder: 'Un password-ai podu', passwordNew: 'Kuraindhadhu 12 ezhuthugal', showPassword: 'Password-ai kaattu', hidePassword: 'Password-ai marai', medium: 'Padikkum mozhi', tamilMedium: 'Tamil medium', englishMedium: 'English medium', submitLogin: 'Vaanga, padikkalaam', submitSignup: 'En payanathai thodangu', noSave: 'Idhu preview mattum. Un details anuppavum save pannavum illa.', dismiss: 'Seidhiyai moodu', newHere: 'Inga pudhusa?', existing: 'Erkanave kanakku irukka?', freshStart: 'Pudhusa thodangu', ownPace: 'Ore paadathittam. Un sondha vegam.', classLine: 'Tamil & English vazhi · Tamil Nadu 10-aam vaguppu',
  },
  en: {
    tagline: 'Made for the way you learn.', board: 'TAMIL NADU STATE BOARD', navigation: 'Learning levels', menu: 'Menu', closeMenu: 'Close menu', languageLabel: 'Language', homeLabel: 'Padi and Go home',
    routes: { chat: 'Learn', practice: 'Practise', tests: 'Test', progress: 'Improve', login: 'Log in' },
    routeNotes: { chat: 'Chatbot', practice: 'Topic questions', tests: 'Mock tests', progress: 'Revision & progress' },
    directAccess: 'Go to learning preview', sampleComing: 'This sample module is added in the next task.',
    loginKicker: 'YOUR SPACE TO GROW', loginTitle: 'Welcome back.', signupTitle: 'A new beginning.', loginSubtitle: 'Good to see you. Let’s turn a new page.', signupSubtitle: 'Your learning journey starts with you.',
    login: 'Log in', signup: 'Create account', name: 'Your name', namePlaceholder: 'What should we call you?', email: 'Email address', password: 'Password', passwordPlaceholder: 'Enter your password', passwordNew: 'At least 12 characters', showPassword: 'Show password', hidePassword: 'Hide password', medium: 'Study medium', tamilMedium: 'Tamil medium', englishMedium: 'English medium', submitLogin: 'Let’s get learning', submitSignup: 'Start my chapter', noSave: 'This is a preview. No details have been sent or saved.', dismiss: 'Dismiss message', newHere: 'New around here?', existing: 'Already have an account?', freshStart: 'Make a fresh start', ownPace: 'One syllabus. Your own pace.', classLine: 'Tamil & English medium · Tamil Nadu Class 10',
  },
  ta: {
    tagline: 'உன் கற்றலுக்காக உருவாக்கப்பட்டது.', board: 'தமிழ்நாடு மாநிலப் பாடத்திட்டம்', navigation: 'கற்றல் நிலைகள்', menu: 'பட்டியல்', closeMenu: 'பட்டியலை மூடு', languageLabel: 'மொழி', homeLabel: 'படி அண்ட் கோ முகப்பு',
    routes: { chat: 'கற்போம்', practice: 'பயிற்சி', tests: 'தேர்வு', progress: 'மேம்பாடு', login: 'உள்நுழை' },
    routeNotes: { chat: 'உரையாடல் ஆசிரியர்', practice: 'தலைப்புக் கேள்விகள்', tests: 'மாதிரித் தேர்வுகள்', progress: 'மீள்பார்வை & முன்னேற்றம்' },
    directAccess: 'கற்றல் முன்னோட்டத்திற்குச் செல்', sampleComing: 'இந்த மாதிரித் தொகுதி அடுத்த பணியில் சேர்க்கப்படும்.',
    loginKicker: 'நீ வளர்வதற்கான இடம்', loginTitle: 'மீண்டும் வருக.', signupTitle: 'புதிய தொடக்கம்.', loginSubtitle: 'உன்னைப் பார்ப்பதில் மகிழ்ச்சி. அடுத்த பக்கம் செல்லலாம்.', signupSubtitle: 'உன் கற்றல் பயணம் உன்னிடம் தொடங்குகிறது.',
    login: 'உள்நுழை', signup: 'கணக்கு உருவாக்கு', name: 'உன் பெயர்', namePlaceholder: 'உன்னை எப்படி அழைக்கலாம்?', email: 'மின்னஞ்சல் முகவரி', password: 'கடவுச்சொல்', passwordPlaceholder: 'உன் கடவுச்சொல்லை இடு', passwordNew: 'குறைந்தது 12 எழுத்துகள்', showPassword: 'கடவுச்சொல்லைக் காட்டு', hidePassword: 'கடவுச்சொல்லை மறை', medium: 'பயிற்று மொழி', tamilMedium: 'தமிழ் வழி', englishMedium: 'ஆங்கில வழி', submitLogin: 'கற்கத் தொடங்கலாம்', submitSignup: 'என் பயணத்தைத் தொடங்கு', noSave: 'இது முன்னோட்டம் மட்டும். உன் விவரங்கள் அனுப்பப்படவோ சேமிக்கப்படவோ இல்லை.', dismiss: 'செய்தியை மூடு', newHere: 'இங்கு புதியவரா?', existing: 'ஏற்கனவே கணக்கு உள்ளதா?', freshStart: 'புதிதாகத் தொடங்கு', ownPace: 'ஒரே பாடத்திட்டம். உன் சொந்த வேகம்.', classLine: 'தமிழ் & ஆங்கில வழி · தமிழ்நாடு 10ஆம் வகுப்பு',
  },
};
