const copy = {
  'ta-Latn': {
    level: 'MOCK TESTS · LEVEL 3',
    title: 'Test-ku ready-aagalam.',
    chooseSubject: 'Oru paadathai therndhedu',
    available: 'Available test',
    empty: 'Indha paadathukku mock test innum ready aagala.',
    questions: 'kelvigal',
    minutes: 'nimidangal',
    start: 'Test-ai thodangu',
    back: 'Test pattiyalukku thirumbu',
    instructions: 'Thodangum mun',
    instructionItems: [
      'Ella kelvigalukkum badhil sollu.',
      'Timer thodangina piragu neram odum.',
      'Mudikkum mun badhilgalai paarthu urudhi sei.',
    ],
    timeLeft: 'Meedhi neram', question: 'Kelvi', of: '/', answered: 'badhil sonnadhu',
    previous: 'Mundhiya kelvi', next: 'Adutha kelvi', submit: 'Test-ai samarpikkavum',
    confirmTitle: 'Samarpikka ready-aa?', confirmBody: 'Samarpiththa piragu badhilgalai maatra mudiyaadhu.',
    unanswered: 'Badhil sollaadha kelvigal', noneUnanswered: 'Ella kelvigalukkum badhil solliyachu.',
    cancel: 'Thirumbi paaru', confirm: 'Aam, samarpikkavum', submitted: 'Test samarpikkappattadhu.', expired: 'Neram mudindhadhaal test thaanaga samarpikkappattadhu.',
    results: 'Mudivugal', score: 'Un score', yourAnswer: 'Un badhil', correctAnswer: 'Sariyaana badhil',
    notAnswered: 'Badhil illai', explanation: 'Vilakkam', backToTests: 'Veru test-ai paaru',
  },
  en: {
    level: 'MOCK TESTS · LEVEL 3',
    title: 'Get ready for your test.',
    chooseSubject: 'Choose a subject',
    available: 'Available test',
    empty: 'A mock test is not available for this subject yet.',
    questions: 'questions',
    minutes: 'minutes',
    start: 'Start test',
    back: 'Back to test list',
    instructions: 'Before you begin',
    instructionItems: [
      'Answer every question.',
      'The timer starts after you begin.',
      'Review your answers before you submit.',
    ],
    timeLeft: 'Time left', question: 'Question', of: 'of', answered: 'answered',
    previous: 'Previous question', next: 'Next question', submit: 'Submit test',
    confirmTitle: 'Ready to submit?', confirmBody: 'You cannot change answers after submitting.',
    unanswered: 'Unanswered questions', noneUnanswered: 'You answered every question.',
    cancel: 'Keep reviewing', confirm: 'Yes, submit', submitted: 'Test submitted.', expired: 'Time ended, so your test was submitted automatically.',
    results: 'Results', score: 'Your score', yourAnswer: 'Your answer', correctAnswer: 'Correct answer',
    notAnswered: 'Not answered', explanation: 'Explanation', backToTests: 'Back to test list',
  },
  ta: {
    level: 'மாதிரித் தேர்வுகள் · நிலை 3',
    title: 'தேர்வுக்குத் தயாராகலாம்.',
    chooseSubject: 'ஒரு பாடத்தைத் தேர்ந்தெடுக்கவும்',
    available: 'கிடைக்கும் தேர்வு',
    empty: 'இந்தப் பாடத்திற்கான மாதிரித் தேர்வு இன்னும் தயாராகவில்லை.',
    questions: 'கேள்விகள்',
    minutes: 'நிமிடங்கள்',
    start: 'தேர்வைத் தொடங்கு',
    back: 'தேர்வுப் பட்டியலுக்குத் திரும்பு',
    instructions: 'தொடங்கும் முன்',
    instructionItems: [
      'எல்லாக் கேள்விகளுக்கும் பதிலளிக்கவும்.',
      'நீங்கள் தொடங்கிய பிறகு நேரம் ஓடத் தொடங்கும்.',
      'சமர்ப்பிக்கும் முன் பதில்களைப் பார்க்கவும்.',
    ],
    timeLeft: 'மீதமுள்ள நேரம்', question: 'கேள்வி', of: '/', answered: 'பதிலளித்தவை',
    previous: 'முந்தைய கேள்வி', next: 'அடுத்த கேள்வி', submit: 'தேர்வைச் சமர்ப்பி',
    confirmTitle: 'சமர்ப்பிக்கத் தயாரா?', confirmBody: 'சமர்ப்பித்த பிறகு பதில்களை மாற்ற முடியாது.',
    unanswered: 'பதிலளிக்காத கேள்விகள்', noneUnanswered: 'எல்லாக் கேள்விகளுக்கும் பதிலளித்துள்ளீர்கள்.',
    cancel: 'மீண்டும் சரிபார்', confirm: 'ஆம், சமர்ப்பி', submitted: 'தேர்வு சமர்ப்பிக்கப்பட்டது.', expired: 'நேரம் முடிந்ததால் தேர்வு தானாகச் சமர்ப்பிக்கப்பட்டது.',
    results: 'முடிவுகள்', score: 'உங்கள் மதிப்பெண்', yourAnswer: 'உங்கள் பதில்', correctAnswer: 'சரியான பதில்',
    notAnswered: 'பதிலளிக்கவில்லை', explanation: 'விளக்கம்', backToTests: 'தேர்வுப் பட்டியலுக்குத் திரும்பு',
  },
};

export default copy;
